const NAMES: ReadonlyArray<readonly [string, string]> = [
  ["monkey d. luffy", "路飞"],
  ["luffy", "路飞"],
  ["roronoa zoro", "索隆"],
  ["zoro", "索隆"],
  ["nami", "娜美"],
  ["usopp", "乌索普"],
  ["vinsmoke sanji", "山治"],
  ["sanji", "山治"],
  ["tony tony chopper", "乔巴"],
  ["chopper", "乔巴"],
  ["nico robin", "罗宾"],
  ["robin", "罗宾"],
  ["franky", "弗兰奇"],
  ["brook", "布鲁克"],
  ["jinbe", "甚平"],
  ["trafalgar law", "罗"],
  ["portgas d. ace", "艾斯"],
  ["ace", "艾斯"],
  ["sabo", "萨博"],
  ["boa hancock", "汉库克"],
  ["hancock", "汉库克"],
  ["shanks", "香克斯"],
  ["dracule mihawk", "米霍克"],
  ["mihawk", "米霍克"],
  ["donquixote doflamingo", "多弗朗明哥"],
  ["doflamingo", "多弗朗明哥"],
  ["yamato", "大和"],
  ["eustass kid", "基德"],
  ["kaido", "凯多"],
  ["chiikawa", "吉伊卡哇"],
  ["hachiware", "小八"],
  ["usagi", "乌萨奇"],
  ["momonga", "飞鼠"],
  ["rakko", "海獭"],
  ["kurimanju", "栗子馒头"],
  ["shisa", "风狮爷"],
  ["furuhonya", "古本屋"],
  ["kabutomushi", "独角仙"],
  ["pochette armor", "小包盔甲"],
  ["ramen armor", "拉面盔甲"],
  ["pajama parties leader", "睡衣派对队长"],
  ["dr. smolder bravestone", "布雷夫斯通"],
  ["smolder bravestone", "布雷夫斯通"],
  ["ruby roundhouse", "露比"],
  ['franklin "mouse" finbar', "芬巴"],
  ["franklin finbar", "芬巴"],
  ["professor shelly oberon", "奥伯伦"],
  ["shelly oberon", "奥伯伦"],
  ['jefferson "seaplane" mcdonough', "麦克多诺"],
  ["nigel billingsley", "比林斯利"],
  ["russell van pelt", "范佩尔特"],
  ["paul atreides", "保罗"],
  ["lady jessica", "杰西卡"],
  ["chani", "契妮"],
  ["duke leto atreides", "莱托"],
  ["leto atreides", "莱托"],
  ["duncan idaho", "邓肯"],
  ["gurney halleck", "葛尼"],
  ["stilgar", "斯第尔格"],
  ["baron vladimir harkonnen", "哈克南男爵"],
  ["vladimir harkonnen", "哈克南"],
  ["glossu rabban", "拉班"],
  ["dr. liet kynes", "凯恩斯"],
  ["liet kynes", "凯恩斯"],
  ["reverend mother mohiam", "莫希阿姆"],
  ["dr. wellington yueh", "岳"],
  ["wellington yueh", "岳"],
  ["thufir hawat", "哈瓦特"],
  ["piter de vries", "彼得"],
  ["one piece", "海贼王"],
  ["jumanji", "勇敢者游戏"],
  ["dune", "沙丘"],
];

const PHRASES: ReadonlyArray<readonly [string, string]> = [
  ["open red vest", "红色开襟背心"],
  ["blue shorts", "蓝色短裤"],
  ["straw hat", "草帽"],
  ["green haramaki", "绿色腹卷"],
  ["black bandana", "黑色头巾"],
  ["three swords", "三刀流佩刀"],
  ["striped overalls", "条纹背带裤"],
  ["blue-and-white striped top", "蓝白条纹上衣"],
  ["striped top", "条纹上衣"],
  ["dress shoes", "皮鞋"],
  ["black suit", "黑色西装"],
  ["pink hat", "粉色帽子"],
  ["cowboy hat", "牛仔帽"],
  ["hawaiian shirt", "夏威夷衫"],
  ["top hat", "高礼帽"],
  ["afro wig", "爆炸头假发"],
  ["white hat", "白色帽子"],
  ["black coat", "黑色外套"],
  ["dark coat", "深色外套"],
  ["orange hat", "橙色帽子"],
  ["open shirt", "开襟衬衫"],
  ["blue coat", "蓝色外套"],
  ["red cape", "红色披风"],
  ["dark cloak", "深色斗篷"],
  ["wide black hat", "黑色宽檐帽"],
  ["pink coat", "粉色外套"],
  ["spiked club", "狼牙棒"],
  ["fur collar", "毛领"],
  ["metal arm", "金属义肢"],
  ["purple vest", "紫色背心"],
  ["leather vest", "皮背心"],
  ["khaki trousers", "卡其裤"],
  ["khaki shorts", "卡其短裤"],
  ["combat boots", "作战靴"],
  ["utility vest", "机能背心"],
  ["flight jacket", "飞行夹克"],
  ["aviator scarf", "飞行员围巾"],
  ["pilot cap", "飞行员帽"],
  ["safari suit", "狩猎套装"],
  ["pith helmet", "遮阳盔"],
  ["stillsuit", "蒸馏服"],
  ["military uniform", "军装"],
  ["black robes", "黑色长袍"],
  ["doctor coat", "医生外套"],
  ["open robe", "开襟长袍"],
  ["metal pipe", "金属棍"],
  ["pajama", "睡衣"],
  ["pajamas", "睡衣"],
  ["cosplay", "角色扮演"],
];

const WORDS: Record<string, string> = {
  straw: "草",
  hat: "帽子",
  hats: "帽子",
  cap: "帽",
  vest: "背心",
  shorts: "短裤",
  skirt: "裙子",
  dress: "连衣裙",
  gown: "礼服",
  robe: "长袍",
  robes: "长袍",
  kimono: "和服",
  qipao: "旗袍",
  suit: "西装",
  shirt: "衬衫",
  coat: "外套",
  jacket: "夹克",
  cloak: "斗篷",
  cape: "披风",
  veil: "面纱",
  scarf: "围巾",
  tie: "领带",
  belt: "腰带",
  boots: "靴子",
  boot: "靴子",
  shoes: "鞋",
  shoe: "鞋",
  sandals: "凉鞋",
  sandal: "凉鞋",
  oxfords: "牛津鞋",
  sneakers: "运动鞋",
  wig: "假发",
  hair: "假发",
  goggles: "护目镜",
  glasses: "眼镜",
  sunglasses: "太阳镜",
  helmet: "头盔",
  mask: "面具",
  armor: "盔甲",
  armour: "盔甲",
  sword: "剑",
  swords: "剑",
  knife: "刀",
  staff: "法杖",
  cane: "手杖",
  club: "棍",
  backpack: "背包",
  bag: "包",
  gloves: "手套",
  stockings: "丝袜",
  necklace: "项链",
  earrings: "耳环",
  crown: "皇冠",
  uniform: "制服",
  trousers: "裤子",
  pants: "裤子",
  hoodie: "卫衣",
  sweater: "毛衣",
  cardigan: "开衫",
  blouse: "上衣",
  top: "上衣",
  apron: "围裙",
  overalls: "背带裤",
  bandana: "头巾",
  haramaki: "腹卷",
  bow: "蝴蝶结",
  ribbon: "丝带",
  feather: "羽毛",
  horns: "角饰",
  horn: "角",
  beads: "珠串",
  pendant: "吊坠",
  holster: "枪套",
  open: "开襟",
  red: "红色",
  blue: "蓝色",
  green: "绿色",
  black: "黑色",
  white: "白色",
  orange: "橙色",
  purple: "紫色",
  pink: "粉色",
  yellow: "黄色",
  brown: "棕色",
  khaki: "卡其",
  cream: "米色",
  olive: "橄榄色",
  gold: "金色",
  silver: "银色",
  grey: "灰色",
  gray: "灰色",
  dark: "深色",
  light: "浅色",
  bright: "鲜艳",
  long: "长",
  short: "短",
  wide: "宽",
  small: "小",
  large: "大",
  leather: "皮",
  metal: "金属",
  wool: "羊毛",
  cotton: "棉",
  silk: "丝绸",
  striped: "条纹",
  spotted: "斑点",
  patterned: "花纹",
  formal: "正式",
  costume: "服装",
  outfit: "套装",
  cos: "角色扮演",
  prop: "道具",
  props: "道具",
};

const STOP = new Set([
  "a",
  "an",
  "the",
  "and",
  "or",
  "with",
  "on",
  "of",
  "in",
  "at",
  "for",
  "to",
  "from",
  "by",
  "worn",
  "marked",
  "covering",
  "under",
  "over",
  "along",
  "one",
  "his",
  "her",
  "their",
]);

const S2T: Record<string, string> = {
  飞: "飛",
  龙: "龍",
  罗: "羅",
  乔: "喬",
  亚: "亞",
  乌: "烏",
  泽: "澤",
  头: "頭",
  带: "帶",
  裤: "褲",
  衬: "襯",
  红: "紅",
  蓝: "藍",
  绿: "綠",
  黄: "黃",
  发: "發",
  长: "長",
  东: "東",
  车: "車",
  马: "馬",
  鱼: "魚",
  鸟: "鳥",
  剑: "劍",
  战: "戰",
  门: "門",
  贝: "貝",
  见: "見",
  页: "頁",
  风: "風",
  饭: "飯",
  饮: "飲",
  饰: "飾",
  装: "裝",
  卫: "衛",
  镜: "鏡",
  袜: "襪",
  领: "領",
  夹: "夾",
  壳: "殼",
  体: "體",
  国: "國",
  华: "華",
  万: "萬",
  与: "與",
  为: "為",
  这: "這",
  个: "個",
  时: "時",
  间: "間",
  开: "開",
  关: "關",
  电: "電",
  视: "視",
  云: "雲",
  后: "後",
  里: "裡",
  干: "乾",
  凉: "涼",
  猎: "獵",
  军: "軍",
  医: "醫",
  萨: "薩",
  博: "博",
  汉: "漢",
  库: "庫",
  克: "克",
  香: "香",
  兰: "蘭",
  奇: "奇",
  纳: "納",
  美: "美",
  索: "索",
  隆: "隆",
  娅: "婭",
  丽: "麗",
  丝: "絲",
  贼: "賊",
  胆: "膽",
  勇: "勇",
  戏: "戲",
  游: "遊",
  邓: "鄧",
  肯: "肯",
  莱: "萊",
  约: "約",
  瑟: "瑟",
  佩: "佩",
  尔: "爾",
  特: "特",
  杰: "傑",
  西: "西",
  卡: "卡",
  契: "契",
  妮: "妮",
  斯: "斯",
  第: "第",
  格: "格",
  哈: "哈",
  瓦: "瓦",
  彼: "彼",
  得: "得",
  岳: "岳",
  凯: "凱",
  恩: "恩",
  莫: "莫",
  希: "希",
  阿: "阿",
  姆: "姆",
  男: "男",
  爵: "爵",
  拉: "拉",
  班: "班",
  基: "基",
  德: "德",
  多: "多",
  弗: "弗",
  朗: "朗",
  明: "明",
  哥: "哥",
  大: "大",
  和: "和",
  甚: "甚",
  平: "平",
  布: "布",
  鲁: "魯",
  艾: "艾",
  鹰: "鷹",
  眼: "眼",
  吉: "吉",
  伊: "伊",
  哇: "哇",
  獭: "獺",
  栗: "栗",
  馒: "饅",
  独: "獨",
  仙: "仙",
  盔: "盔",
  甲: "甲",
  睡: "睡",
  衣: "衣",
  队: "隊",
  露: "露",
  比: "比",
  奥: "奧",
  伯: "伯",
  伦: "倫",
  麦: "麥",
  盗: "盜",
};

const NAME_PATTERNS = [...NAMES].sort((a, b) => b[0].length - a[0].length);
const PHRASE_PATTERNS = [...PHRASES].sort((a, b) => b[0].length - a[0].length);

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function boundary(text: string, start: number, length: number): boolean {
  const before = start === 0 ? "" : text[start - 1] ?? "";
  const after = text[start + length] ?? "";
  const letter = /[a-z0-9]/i;
  return !letter.test(before) && !letter.test(after);
}

function translateFragment(text: string): string {
  const lower = text.toLowerCase();
  const tokens: string[] = [];
  let index = 0;
  while (index < text.length) {
    const current = text[index] ?? "";
    if (/\s/.test(current)) {
      index += 1;
      continue;
    }
    if (/[\u3400-\u9fff]/.test(current)) {
      const run = /^[\u3400-\u9fff·・]+/.exec(text.slice(index));
      if (run) {
        tokens.push(run[0]);
        index += run[0].length;
        continue;
      }
    }
    let matched = false;
    for (const [english, chinese] of PHRASE_PATTERNS) {
      if (lower.startsWith(english, index) && boundary(lower, index, english.length)) {
        tokens.push(chinese);
        index += english.length;
        matched = true;
        break;
      }
    }
    if (matched) continue;
    const word = /^[a-z0-9+'.-]+/i.exec(text.slice(index));
    if (!word) {
      index += 1;
      continue;
    }
    const token = word[0].toLowerCase();
    if (!STOP.has(token)) tokens.push(WORDS[token] ?? word[0]);
    index += word[0].length;
  }
  return tokens.join(" ").replace(/\s+/g, " ").trim();
}

export function toTraditional(text: string): string {
  return [...text].map((char) => S2T[char] ?? char).join("");
}

export function translateShopQuery(english: string, script: "hans" | "hant"): string {
  let text = english;
  for (const [name, chinese] of NAME_PATTERNS) {
    text = text.replace(new RegExp(`(^|[^A-Za-z0-9])${escapeRegExp(name)}(?![A-Za-z0-9])`, "ig"), `$1${chinese}`);
  }
  const hans = translateFragment(text);
  return script === "hant" ? toTraditional(hans) : hans;
}
